"""EPW file writer."""

from datetime import datetime
from typing import Any

from xweather2epw.logcfg import init_logging

init_logging()


class EPWWriter:
    """Writer for EnergyPlus Weather (EPW) files."""

    # Default values for missing data as per EPW format specification
    MISSING_TEMP = 99.9
    MISSING_PRESSURE = 999999
    MISSING_HUMIDITY = 999
    MISSING_RADIATION = 9999
    MISSING_WIND_SPEED = 999
    MISSING_WIND_DIR = 999
    MISSING_SKY_COVER = 99
    MISSING_VISIBILITY = 9999
    MISSING_CEILING = 99999
    MISSING_PRECIP = 999
    MISSING_SNOW = 999

    def __init__(self, weather_data: dict[str, Any], latitude: float, longitude: float):
        """Initialize EPW writer.

        :param weather_data: Weather data from XWeather API
        :param latitude: Location latitude
        :param longitude: Location longitude
        """
        self.weather_data = weather_data
        self.latitude = latitude
        self.longitude = longitude

    def write(self, output_path: str):
        """Write EPW file.

        Args:
            output_path: Path to output EPW file
        """
        with open(output_path, "w", newline="\n") as f:
            # Write headers
            self._write_location_header(f)
            self._write_design_conditions_header(f)
            self._write_typical_extreme_periods_header(f)
            self._write_ground_temperatures_header(f)
            self._write_holidays_header(f)
            self._write_comments_header(f)
            self._write_data_periods_header(f)

            # Write weather data
            self._write_weather_data(f)

    def _write_location_header(self, f):
        """Write LOCATION header line."""
        place = self.weather_data.get("place", {})
        profile = self.weather_data.get("profile", {})

        # Extract location information
        city = place.get("name", "Unknown")
        state = place.get("state", "")
        country = place.get("country", "")

        # Build city name
        if state:
            city_full = f"{city}/{state}"
        else:
            city_full = city

        # Get timezone offset (default to 0 if not available)
        tzoffset_sec = profile.get("tzoffset", 0) if profile else 0
        if isinstance(tzoffset_sec, (int, float)):
            timezone = tzoffset_sec / 3600  # Convert seconds to hours
        else:
            timezone = 0

        # Get elevation (default to 0 if not available)
        elevation = profile.get("elevM", 0) if profile else 0

        # WMO number (not available from XWeather, use 999999)
        wmo = 999999

        # Data source
        source = "XWeather"

        f.write(
            f"LOCATION,{city_full},{state},{country},{source},"
            f"{wmo},{self.latitude},{self.longitude},{timezone},{elevation}\n"
        )

    def _write_design_conditions_header(self, f):
        """Write DESIGN CONDITIONS header (empty for this implementation)."""
        f.write("DESIGN CONDITIONS,0\n")

    def _write_typical_extreme_periods_header(self, f):
        """Write TYPICAL/EXTREME PERIODS header (empty for this implementation)."""
        f.write("TYPICAL/EXTREME PERIODS,0\n")

    def _write_ground_temperatures_header(self, f):
        """Write GROUND TEMPERATURES header (set to 0 as per requirements)."""
        f.write("GROUND TEMPERATURES,0\n")

    def _write_holidays_header(self, f):
        """Write HOLIDAYS/DAYLIGHT SAVINGS header (empty for this implementation)."""
        periods = self.weather_data.get("periods", [])
        first_period = periods[0]
        first_date = self._parse_iso_datetime(first_period.get("dateTimeISO", ""))
        is_leap_year = first_date.year % 4 == 0 if first_date else False
        is_leap_year = "Yes" if is_leap_year else "No"
        f.write(f"HOLIDAYS/DAYLIGHT SAVINGS,{is_leap_year},0,0,0\n")

    def _write_comments_header(self, f):
        """Write COMMENTS headers."""
        f.write("COMMENTS 1,Generated by xweather2epw - XWeather to EPW Converter\n")
        f.write("COMMENTS 2,Weather data sourced from XWeather API (https://www.xweather.com/)\n")

    def _write_data_periods_header(self, f):
        """Write DATA PERIODS header."""
        periods = self.weather_data.get("periods", [])

        if not periods:
            # No data, write minimal header
            f.write("DATA PERIODS,1,1,Data,Sunday,1/1,12/31\n")
            return

        # Get date range from periods
        first_period = periods[0]
        last_period = periods[-1]

        # Parse dates
        first_date = self._parse_iso_datetime(first_period.get("dateTimeISO", ""))
        last_date = self._parse_iso_datetime(last_period.get("dateTimeISO", ""))

        if first_date and last_date:
            start_str = f"{first_date.month}/{first_date.day}"
            end_str = f"{last_date.month}/{last_date.day}"
            # Get day of week for start date (Monday=0)
            day_of_week = [
                "Monday",
                "Tuesday",
                "Wednesday",
                "Thursday",
                "Friday",
                "Saturday",
                "Sunday",
            ][first_date.weekday()]
        else:
            start_str = "1/1"
            end_str = "12/31"
            day_of_week = "Sunday"

        f.write(f"DATA PERIODS,1,1,Data,{day_of_week},{start_str},{end_str}\n")

    def _write_weather_data(self, f):
        """Write hourly weather data records."""
        periods = self.weather_data.get("periods", [])

        if not periods:
            return

        for period in periods:
            self._write_weather_record(f, period)

    def _write_weather_record(self, f, period: dict[str, Any]):
        """Write a single weather data record.

        Args:
            f: File handle
            period: Weather period data from API
        """
        # Parse timestamp
        dt = self._parse_iso_datetime(period.get("dateTimeISO", ""))
        if not dt:
            return  # Skip invalid records

        year = dt.year
        month = dt.month
        day = dt.day
        hour = dt.hour + 1  # EPW hours are 1-24
        minute = dt.minute if dt.minute else 0

        # Data source and uncertainty flags (not used)
        data_source_uncertainty = "9"

        # Temperature data (°C)
        dry_bulb = round(period.get("tempC", self.MISSING_TEMP), 1)
        dew_point = round(period.get("dewpointC", self.MISSING_TEMP), 1)

        # Humidity (%)
        humidity = round(period.get("humidity", self.MISSING_HUMIDITY), 1)

        # Atmospheric pressure (Pa) - XWeather provides in mb, convert to Pa
        pressure_mb = period.get("pressureMB")
        if pressure_mb is not None:
            pressure = pressure_mb * 100  # mb to Pa
        else:
            pressure = self.MISSING_PRESSURE
        pressure = round(pressure, 0)

        # Radiation data (Wh/m²) - extract from solrad field if available
        solrad = period.get("solrad", {})

        # EPW expects Wh/m², XWeather provides W/m² (instantaneous)
        # For hourly data, W/m² is approximately equal to Wh/m²
        global_horizontal = solrad.get("ghiWM2", self.MISSING_RADIATION)
        direct_normal = solrad.get("dniWM2", self.MISSING_RADIATION)
        diffuse_horizontal = solrad.get("dhiWM2", self.MISSING_RADIATION)

        # Extraterrestrial and infrared radiation not available from API
        etr_horizontal = self.MISSING_RADIATION
        etr_direct = self.MISSING_RADIATION
        ir_horizontal = self.MISSING_RADIATION

        # Illuminance data (lux) - using missing values
        global_horiz_illum = self.MISSING_RADIATION
        direct_normal_illum = self.MISSING_RADIATION
        diffuse_horiz_illum = self.MISSING_RADIATION
        zenith_luminance = self.MISSING_RADIATION

        # Wind data
        wind_dir = period.get("windDirDEG", self.MISSING_WIND_DIR)

        # Wind speed (m/s) - XWeather provides in kph, convert to m/s
        wind_kph = period.get("windSpeedKPH")
        if wind_kph is not None:
            wind_speed = wind_kph / 3.6  # kph to m/s
        else:
            wind_speed = self.MISSING_WIND_SPEED
        wind_speed = round(wind_speed, 1)

        # Sky cover data (tenths) - XWeather provides cloud cover in %, convert to tenths
        cloud_cover_pct = period.get("cloudsCovered")
        if cloud_cover_pct is not None:
            sky_cover = int(cloud_cover_pct / 10)  # % to tenths
        else:
            sky_cover = self.MISSING_SKY_COVER

        opaque_sky_cover = sky_cover  # Use same value for opaque cover

        # Visibility (km)
        visibility = period.get("visibilityKM", self.MISSING_VISIBILITY)

        # Ceiling height (m)
        ceiling = self.MISSING_CEILING

        # Present weather observation and codes
        weather_obs = 0
        weather_codes = 999999999

        # Precipitable water (mm)
        precipitable_water = self.MISSING_PRECIP

        # Aerosol optical depth (thousandths)
        aerosol_optical = self.MISSING_PRECIP

        # Snow depth (cm)
        snow_depth_cm = period.get("snowDepthCM", self.MISSING_SNOW)

        # Days since last snowfall
        days_last_snow = self.MISSING_SNOW

        # Albedo
        albedo = self.MISSING_PRECIP

        # Liquid precipitation (mm and hr)
        precip_mm = period.get("precipMM")
        if precip_mm is not None:
            liquid_precip = precip_mm
            liquid_precip_qty = 1  # Assume 1 hour
        else:
            liquid_precip = 0
            liquid_precip_qty = 0

        # Format record
        record = (
            f"{year},{month},{day},{hour},{minute},"
            f"{data_source_uncertainty},"
            f"{dry_bulb},{dew_point},{humidity},{pressure},"
            f"{etr_horizontal},{etr_direct},{ir_horizontal},"
            f"{global_horizontal},{direct_normal},{diffuse_horizontal},"
            f"{global_horiz_illum},{direct_normal_illum},{diffuse_horiz_illum},{zenith_luminance},"
            f"{wind_dir},{wind_speed},"
            f"{sky_cover},{opaque_sky_cover},"
            f"{visibility},{ceiling},"
            f"{weather_obs},{weather_codes},"
            f"{precipitable_water},{aerosol_optical},{snow_depth_cm},{days_last_snow},"
            f"{albedo},{liquid_precip},{liquid_precip_qty}\n"
        )

        f.write(record)

    def _parse_iso_datetime(self, iso_string: str) -> datetime:
        """Parse ISO datetime string.

        Args:
            iso_string: ISO format datetime string

        Returns:
            datetime object or None if parsing fails
        """
        if not iso_string:
            return None

        try:
            # Handle 'Z' timezone indicator (UTC)
            # Note: We strip timezone info as EPW uses naive timestamps
            if iso_string.endswith("Z"):
                iso_string = iso_string[:-1]  # Remove 'Z'

            # Try parsing with timezone info
            # Format: "2024-02-19T18:00:00-06:00"
            if "+" in iso_string or iso_string.count("-") > 2:
                # Has timezone, strip it for simplicity
                # EPW format uses local time without timezone
                dt_part = iso_string[:19]  # Get YYYY-MM-DDTHH:MM:SS part
                return datetime.strptime(dt_part, "%Y-%m-%dT%H:%M:%S")
            else:
                return datetime.strptime(iso_string, "%Y-%m-%dT%H:%M:%S")
        except ValueError:
            return None
